### ISSUE TITLE
Demo does not run

### ISSUE THREAD

**Issue by zawsx** [haxiomic/GPU-Fluid-Experiments#13]
http://haxiomic.github.io/GPU-Fluid-Experiments/html5/ does not produce any moving graphics, just the standard screen with the controls.

**Comment by haxiomic** [comment]
Does anything happen when you click and drag?

**Comment by zawsx** [comment]
Doh! Sorry, I knew I was an idiot when I posted this issue and did try a few things first, including installing Haxe locally so see if there was an obvious bug in the code I could fix. As there may be one or two as slow on the uptake as me, who don't realise that the demo needs 'starting', maybe a splash screen or a note in the controls box?

**Comment by haxiomic** [comment]
:P, yeah, you're right - I've had the same feedback from others too. I think I'll go with a message that appears in the middle and fades out the first time you load it

**Comment by zawsx** [comment]
Or maybe some automatic typing in the fluid itself on startup?
